-- TapeReviewer — Supabase Postgres schema
-- Run this once in the Supabase dashboard → SQL Editor → New query → Run.
-- Ported from the original SQLite schema. Timestamps are kept as TEXT (ISO strings)
-- to preserve the app's original naive-datetime behavior for analytics.

create table if not exists account (
  id         bigint generated by default as identity primary key,
  name       text not null default 'Main',
  currency   text not null default 'USD',
  timezone   text not null default 'America/Los_Angeles',
  created_at text not null default (now()::text)
);

create table if not exists settings (
  key   text primary key,
  value text not null
);

create table if not exists import_batch (
  id                bigint generated by default as identity primary key,
  account_id        bigint not null references account(id) on delete cascade,
  source            text not null check (source in ('das', 'csv')),
  fingerprint       text not null,
  trade_fingerprint text,
  label             text not null default '',
  trade_count       integer not null default 0,
  net_pnl           double precision not null default 0,
  created_at        text not null default (now()::text),
  unique (account_id, fingerprint)
);

create table if not exists trade (
  id               bigint generated by default as identity primary key,
  account_id       bigint not null references account(id) on delete cascade,
  import_batch_id  bigint references import_batch(id) on delete cascade,
  symbol           text not null,
  side             text not null check (side in ('LONG', 'SHORT')),
  opened_at        text not null,
  closed_at        text not null,
  qty              double precision not null,
  avg_entry        double precision not null,
  avg_exit         double precision not null,
  gross_pnl        double precision not null default 0,
  fees             double precision not null default 0,
  net_pnl          double precision not null default 0,
  net_roi          double precision not null default 0,
  notes            text not null default '',
  profit_target    double precision,
  stop_loss        double precision,
  reviewed         boolean not null default false,
  video_path       text,
  video_marker_sec double precision,
  created_at       text not null default (now()::text),
  updated_at       text not null default (now()::text)
);

create index if not exists idx_trade_closed_at    on trade(closed_at);
create index if not exists idx_trade_account       on trade(account_id);
create index if not exists idx_trade_symbol         on trade(symbol);
create index if not exists idx_trade_import_batch   on trade(import_batch_id);
create index if not exists idx_import_batch_fp      on import_batch(account_id, fingerprint);

create table if not exists execution (
  id          bigint generated by default as identity primary key,
  trade_id    bigint not null references trade(id) on delete cascade,
  executed_at text not null,
  side        text not null check (side in ('BUY', 'SELL')),
  qty         double precision not null,
  price       double precision not null,
  fee         double precision not null default 0
);

create table if not exists tag (
  id    bigint generated by default as identity primary key,
  name  text not null unique,
  kind  text not null default 'general',
  color text not null default '#0F8A7A'
);

create table if not exists trade_tag (
  trade_id bigint not null references trade(id) on delete cascade,
  tag_id   bigint not null references tag(id) on delete cascade,
  primary key (trade_id, tag_id)
);

create table if not exists day_journal (
  id         bigint generated by default as identity primary key,
  account_id bigint not null references account(id) on delete cascade,
  trade_date text not null,
  verdict    text check (verdict in ('followed_plan', 'broke_rules', 'no_edge') or verdict is null),
  notes      text not null default '',
  unique (account_id, trade_date)
);

create table if not exists day_media (
  id              bigint generated by default as identity primary key,
  day_journal_id  bigint not null references day_journal(id) on delete cascade,
  relative_path   text not null,
  media_type      text not null default 'video',
  unique (day_journal_id)
);

insert into account (id, name, currency, timezone)
values (1, 'Main', 'USD', 'America/Los_Angeles')
on conflict (id) do nothing;

-- Lock down the auto-generated REST API. The app talks to Supabase only through
-- Next.js route handlers using the service-role key, which bypasses RLS. With RLS
-- on and no policies, the anon/public key can read/write nothing.
alter table account      enable row level security;
alter table settings     enable row level security;
alter table import_batch enable row level security;
alter table trade        enable row level security;
alter table execution    enable row level security;
alter table tag          enable row level security;
alter table trade_tag    enable row level security;
alter table day_journal  enable row level security;
alter table day_media    enable row level security;
